# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Justin Mays
title: Director of Faculty Development 
email: justin@justin-mays.com
website: www.justin-mays.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: 
github_username:  megamays08
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: justin-m-mays
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009-0008-3362-9661

# Additional icon links
additional_links:
#- title: itsgoingto.be
  #icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Justin and I'm a mid-career higher education professional. I have experience in distance/online learning, educational technology, and faculty development/training. I have a passion for learning and am always looking for new opportunities to grow my skills and knowledge.
  I began my career at Georgia Military College as an admissions' counselor. Given the popular online learning preferences among students at the time, I transitioned over to the newly created Georgia Military College Online Campus, eventually serving as the director for the campus and growing their online enrollment across Georgia and into neighboring states. 
  I joined Clayton State University in 2014 as the Director of Distance Learning, was promoted to Director of the Center for Learning and Teaching in 2015, and helped the university successfully prepare and execute their remote learning strategy as COVID shuttered institutions. 
  I became Executive Director in 2022 and had a key role in successfully leading the university through their 2024 SACSCOC Reaffirmation.
content:
  #- title: Projects # Title for the section
    #layout: list # Type of content section (list/text)
    #content:
      #- layout: top-middle
        #title: Super awesome project
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
          #- title:  sproogen/modern-resume-theme
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
          #This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        #description: | # this will include new lines to allow paragraphs
          #I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University System of Georgia eCampus
        link: https://ecampus.usg.edu
        link_text: ecampus.usg.edu
        sub_title: Director, eCampus Faculty Development
        caption: 2024 - Present
        #quote: >
          #Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            I lead a small team of instructional designers and educational developers to develop training and development opportunities for faculty across the University System of Georgia.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Georgia College and State University
        sub_title: BA Political Science
        quote: >
          Georgia College is a public university located in Milledgeville, Georgia. It was founded in 1889 as the Georgia Normal and Industrial College, and is now part of the University System of Georgia and is the public liberal arts university of the state. 
        #description: | # this will include new lines to allow paragraphs
           # Education description... 
      - layout: left
        title: Georgia College and State University
        sub_title: Master of Public Administration (MPA)
        description: | # this will include new lines to allow paragraphs
          I continued my education at Georgia College and State University and earned a Master of Public Administration while serving as the Graduate Assistant for the Office of Admissions.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - 3D Printing
      - Old Homes
      - Axe Throwing

# Footer
footer_show_references: true
references_title: References are available on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
